# Generated by Django 4.0.4 on 2022-05-05 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to='images')),
                ('narrative', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Vids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=1000)),
                ('date', models.DateField(verbose_name='Upload Date')),
                ('remarks', models.CharField(max_length=200, verbose_name='Comments')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('playlist', models.CharField(blank=True, default='uncategorized', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vids',
            },
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_uploaded', models.DateField(verbose_name='Date Uploaded')),
                ('description', models.CharField(max_length=200)),
                ('featured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.vids')),
            ],
            options={
                'verbose_name_plural': 'Featured',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(default='Uncategorized', null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.vids')),
            ],
        ),
    ]
